STUBS_DEFAULT_PATH = 'stubs'
PLAYER_DETECTOR_PATH = 'models/nbl_v3_combined.pt'
BALL_DETECTOR_PATH = 'models/nbl_v3_combined.pt'
COURT_KEYPOINT_DETECTOR_PATH = 'models/court_keypoint_detector.pt'
OUTPUT_VIDEO_PATH = 'output_videos/output_video.mp4'